In [2]:
import pandas as pd
df = pd.read_excel('filmes.xlsx')

df

                                  titulo                  ano
0               1. Um Sonho de Liberdade     1994\n2h 22m\n16
1                   2. O Poderoso Chefão     1972\n2h 55m\n14
2      3. Batman: O Cavaleiro das Trevas     2008\n2h 32m\n12
3         4. O Poderoso Chefão: Parte II     1974\n3h 22m\n14
4            5. 12 Homens e uma Sentença  1957\n1h 36m\nLivre
..                                   ...                  ...
245            246. Na Natureza Selvagem     2007\n2h 28m\n12
246                247. Feitiço do Tempo     1993\n1h 41m\n12
247              248. Histórias Cruzadas     2011\n2h 26m\n12
248                   249. Amores Brutos     2000\n2h 34m\n16
249  250. Rebecca, a Mulher Inesquecível     1940\n2h 10m\n12

[250 rows x 2 columns]

In [3]:

df[['ano', 'duracao', 'classificacao']] = df['ano'].str.split('\n', expand=True)
display(df.head(40))

,titulo,ano,duracao,classificacao
0,1. Um Sonho de Liberdade,1994,2h 22m,16
1,2. O Poderoso Chefão,1972,2h 55m,14
2,3. Batman: O Cavaleiro das Trevas,2008,2h 32m,12
3,4. O Poderoso Chefão: Parte II,1974,3h 22m,14
4,5. 12 Homens e uma Sentença,1957,1h 36m,Livre
5,6. O Senhor dos Anéis: O Retorno do Rei,2003,3h 21m,12
6,7. A Lista de Schindler,1993,3h 15m,14
7,8. Pulp Fiction: Tempo de Violência,1994,2h 34m,18
8,9. O Senhor dos Anéis: A Sociedade do Anel,2001,2h 58m,12
9,10. Três Homens em Conflito,1966,2h 41m,14
10,11. Forrest Gump: O Contador de Histórias,1994,2h 22m,14
11,12. O Senhor dos Anéis: As Duas Torres,2002,2h 59m,12
12,13. Clube da Luta,1999,2h 19m,18
13,14. A Origem,2010,2h 28m,14
14,15. Star Wars: Episódio V - O Império Contra-A...,1980,2h 4m,Livre
15,16. Matrix,1999,2h 16m,14
16,17. Os Bons Companheiros,1990,2h 25m,14
17,18. Interestelar,2014,2h 49m,10
18,19. Um Estranho no Ninho,1975,2h 13m,16
19,20. Seven - Os Sete Crimes Capitais,1995,2h 7m,14
20,21. A Felicidade Não se Compra,1946,2h 10m,Livre
21,22. O Silêncio dos Inocentes,1991,1h 58m,14
22,23. Os Sete Samurais,1954,3h 27m,10
23,24. O Resgate do Soldado Ryan,1998,2h 49m,14
24,25. Cidade de Deus,2002,2h 10m,18
25,26. À Espera de um Milagre,1999,3h 9m,18
26,27. A Vida é Bela,1997,1h 56m,Livre
27,28. O Exterminador do Futuro 2: O Julgamento F...,1991,2h 17m,14
28,29. Star Wars: Episódio IV - Uma Nova Esperança,1977,2h 1m,Livre
29,30. De Volta para o Futuro,1985,1h 56m,Livre
30,31. A Viagem de Chihiro,2001,2h 4m,Livre
31,32. O Pianista,2002,2h 30m,14
32,33. Gladiador,2000,2h 35m,14
33,34. Parasita,2019,2h 12m,16
34,35. Psicose,1960,1h 49m,14
35,36. O Rei Leão,1994,1h 28m,Livre
36,37. Túmulo dos Vagalumes,1988,1h 28m,12
37,38. Os Infiltrados,2006,2h 31m,18
38,39. Whiplash: Em Busca da Perfeição,2014,1h 46m,12
39,40. Harakiri,1962,2h 13m,16

In [4]:
df['titulo'] = df['titulo'].str.replace('. ', '/', n=1)
print(df.head(163))

df[['posicao', 'titulo']] = df['titulo'].str.split('/', expand=True)

df['ano'] = df['ano'].astype(int)
df.info()

df

                                          titulo   ano duracao classificacao
0                        1/Um Sonho de Liberdade  1994  2h 22m            16
1                            2/O Poderoso Chefão  1972  2h 55m            14
2               3/Batman: O Cavaleiro das Trevas  2008  2h 32m            12
3                  4/O Poderoso Chefão: Parte II  1974  3h 22m            14
4                     5/12 Homens e uma Sentença  1957  1h 36m         Livre
..                                           ...   ...     ...           ...
158  159/Monty Python em Busca do Cálice Sagrado  1975  1h 31m         Livre
159                         160/O Homem Elefante  1980   2h 4m            10
160                      161/Disque M para Matar  1954  1h 45m            16
161                       162/...E o Vento Levou  1939  3h 58m         Livre
162                                    163/Klaus  2019  1h 36m            10

[163 rows x 4 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   titulo         250 non-null    object
 1   ano            250 non-null    int64
 2   duracao        250 non-null    object
 3   classificacao  248 non-null    object
 4   posicao        250 non-null    object
dtypes: int64(1), object(4)
memory usage: 9.9+ KB

                             titulo   ano duracao classificacao posicao
0             Um Sonho de Liberdade  1994  2h 22m            16       1
1                 O Poderoso Chefão  1972  2h 55m            14       2
2    Batman: O Cavaleiro das Trevas  2008  2h 32m            12       3
3       O Poderoso Chefão: Parte II  1974  3h 22m            14       4
4          12 Homens e uma Sentença  1957  1h 36m         Livre       5
..                              ...   ...     ...           ...     ...
245            Na Natureza Selvagem  2007  2h 28m            12     246
246                Feitiço do Tempo  1993  1h 41m            12     247
247              Histórias Cruzadas  2011  2h 26m            12     248
248                   Amores Brutos  2000  2h 34m            16     249
249  Rebecca, a Mulher Inesquecível  1940  2h 10m            12     250

[250 rows x 5 columns]

In [5]:
df.to_excel('filmes_limpo.xlsx', index=False)